SocialNetwork.Web/Controllers/DialogsController.cs
using System.Web.Mvc;
using Ninject;
using SocialNetwork.Core.Dependency;
using SocialNetwork.Core.Interfaces;

namespace SocialNetwork.Web.Controllers
{
    [Authorize]
    public class DialogsController : BaseController
    {
        private readonly IDialogsRepository _dialogsRepository = NinjectBindings.Instance.Get<IDialogsRepository>();

        public ActionResult MyDialogs()
        {
            return View();
        }

        public JsonResult GetAllDialogs()
        {
            return Json(_dialogsRepository.GetAllDialogs(CurrentUser.Id));
        }

        public ActionResult OpenDialog(int id = 0)
        {
            ViewBag.Users = new int[] { CurrentUser.Id, id };

            return View();
        }

        public ActionResult OpenDialogByDialogId(int id = 0)
        {
            ViewBag.Users = _dialogsRepository.GetDialogUsers(id);

            return View();
        }

        public JsonResult GetMessages(int[] users)
        {
            return Json(new { messages = _dialogsRepository.GetMessages(users), userData = _dialogsRepository.GetUserMessageViewModel(users) });
        }

        [HttpPost]
        public JsonResult SendMessage(int[] users, string message)
        {
            return Json(_dialogsRepository.SendMessage(users, message, CurrentUser.Id)
                ? new { response = true }
                : new { response = false });
        }
    }
}

SocialNetwork.Web/Controllers/FriendsController.cs
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Ninject;
using SocialNetwork.Core.Cache;
using SocialNetwork.Core.Dependency;
using SocialNetwork.Core.Interfaces;
using SocialNetwork.DataAccess.DbEntity;
using SocialNetwork.Models.Models;

namespace SocialNetwork.Web.Controllers
{
    [Authorize]
    public class FriendsController : BaseController
    {
        private readonly IFriendsRepository _friendsRepository = NinjectBindings.Instance.Get<IFriendsRepository>();

        public ActionResult ShowAllUsers()
        {
            return View();
        }

        public JsonResult GetAllUsers()
        {
            return Json(_friendsRepository.GetAllUsers(CurrentUser.Id));
        }

        public JsonResult GetMyFriends()
        {
            return Json(_friendsRepository.GetMyFriends(CurrentUser.Id));
        }

        public JsonResult GetRequests()
        {
            return Json(_friendsRepository.GetRequests(CurrentUser.Id));
        }

        public JsonResult GetMyRequests()
        {
            return Json(_friendsRepository.GetMyRequests(CurrentUser.Id));
        }

        public JsonResult AddRequestToFriendList(int id)
        {
            var obj = new { response = _friendsRepository.AddRequestToFriendList(CurrentUser.Id, id) };

            return Json(obj);
        }

        public ActionResult ShowMyFriends()
        {
            return View();
        }

        public ActionResult AddRequestToFriendListFromUserPage(int id = 0)
        {
            if (_friendsRepository.AddRequestToFriendList(CurrentUser.Id, id).Equals("false"))
            {
                return RedirectToAction("ErrorCode500", "Error");
            }

            return RedirectToAction("ShowUserPage", "Home", new { id = id });
        }
    }
}

SocialNetwork.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/bootstrap-datepicker.css")
    @Styles.Render("~/Content/Site.css?349")
    @Styles.Render("~/Content/Home/layout.css?356")
    @Styles.Render("~/Content/Login/Login.css?356")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.js")
    @Scripts.Render("~/Scripts/locales/bootstrap-datepicker.ru.min.js")
    @Scripts.Render("~/Scripts/jquery.signalR-2.2.1.min.js")
    @Scripts.Render("~/signalr/hubs")
</head>
<body>
    @RenderSection("SignalR", false)
<div class="main">
    
    <!--Верхний контейнер-->
    <div class="row top-container">
        <ul class="nav nav-pills">
            <li class="col-md-5 text-center" style="font-size: 2em;">Социальная сеть</li>
            @if (Request.IsAuthenticated)
            {
                <li class="text-center" style="margin-left: 28%;">@Html.ActionLink("Выход", "LogOff", "Account", new {}, new {@class = "login-link"})</li>
            }
            else
            {
                <li class="text-center" style="margin-left: 28%;">@Html.ActionLink("Вход", "Login", "Account", new {}, new {@class = "login-link"})</li>
            }
        </ul>
    </div>

    <!--Основной контейнер-->
    <div class="row col-md-8 middle-container">

        <!--Левое меню-->
        @if (@ViewBag.RenderMenu)
        {
            <div class="col-md-3 left-menu">
                <ul class="nav nav-pills nav-stacked">
                    <li>@Html.ActionLink("Моя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Мои друзья", "ShowMyFriends", "Friends")</li>
                    <li>@Html.ActionLink("Мои диалоги", "MyDialogs", "Dialogs")</li>
                    <li>@Html.ActionLink("Редактировать профиль", "EditUserData", "Home")</li>
                    <li>@Html.ActionLink("Все пользователи", "ShowAllUsers", "Friends")</li>
                </ul>
            </div>

            <!--Тело с данными-->
            <div class="col-md-9">
                @RenderBody()
            </div>
        }
        else
        {
            <!--Тело с данными-->
            <div class="col-md-12">
                @RenderBody()
            </div>
        }

    </div>

    <!--Нижний контейнер-->
    <div class="row bottom-container text-center">
        <p>Социальная сеть. 2017г.</p>
    </div>
</div>
</body>
</html>